### PR TITLE
1.0.0 release

### PR DESCRIPTION
**Pull request by jeffpaul**
- [x] Contributing details
- [x] SVG for gutenblox
- [x] Rules
~- [ ] How to order~

### CODE REVIEW

**Comment by RobStino** [comment]
@jeffpaul Added the SVGs.
Noticed my machine added a couple of files to the repo. Tried removing them without luck. Could you have a look for me?
File in both the parent and PDF directory called `Icon?`

**Comment by jeffpaul** [comment]
Thanks @RobStino, I've removed those stray `Icon` files.

**Comment by jeffpaul** [comment]
Methinks that the "how to order" details can probably wait for another PR / release.  @RobStino, that sound good to you?

**Comment by jeffpaul** [comment]
Moved "How to order" to #3, will merge this PR and tag the 1.0.0 release

**Pull request merged**
